
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Coprocessor(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// UART RX //////
	input                       RX,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);

import common_params::*;

logic rdy;
logic start;


logic bootloading;
logic [2:0]dst;
logic [IB_DW - 1 : 0] wdata_data;
logic [ADDRW : 0] wdata_addr;

//=======================================================
//  REG/WIRE declarations
//=======================================================

PLL iPLL(.refclk(CLOCK_50), .rst(~KEY[0]),.outclk_0(clk),.outclk_1(VGA_CLK),
           .locked(pll_locked));
 
rst_synch iRST(.clk(clk),.RST_n(KEY[0]), .pll_locked(pll_locked), .rst_n(rst_n));

Debouncer iDEBOUNCER(.clk(clk), .rst_n(rst_n), .button_in(KEY[1]), .button_pulse(start));

coproc iCOPROC(
	.clk(clk), .rst_n(rst_n & ~bootloading), .VGA_CLK(VGA_CLK), .start(start), .gray(SW[8]), .img_idx(SW[9]), 
    .func(SW[2:0]), .rdy(rdy), .VGA_B(VGA_B), .VGA_G(VGA_G), .VGA_R(VGA_R), .VGA_BLANK_N(VGA_BLANK_N),
	.VGA_SYNC_N(VGA_SYNC_N), .VGA_HS(VGA_HS), .VGA_VS(VGA_VS), 
	.we_boot(dst[0]), .wdata_boot(wdata_data), .waddr_boot(wdata_addr[8:0]), .bootloading(bootloading));

// Bootloader Instantiation
UART_boot Boot(.clk(clk), .rst_n(rst_n), .RX(RX), .wdata_data(wdata_data), .wdata_addr(wdata_addr), 
	.dst(dst), .bootloading(bootloading));

//=======================================================
//  Structural coding
//=======================================================



endmodule
